# add following lines to your configuration.yaml to enable provided config files

python_script:
  #HACS python_script pro
  !include python_script.yaml

# if you use an external mqtt yaml file, you have to add / change this here
mqtt:
  !include mqtt_devices.yaml
